# Source : https://bookdown.org/yihui/rmarkdown-cookbook/parameterized-reports.html

library(fivethirtyeight)
library(tidyverse)
library(rmarkdown)

# gérer le répertoire de destination (le créer au besoin)
dir.create(path = "output",
           showWarnings = FALSE)

# préparer la liste des id et l'identification de l'année

id <- bad_drivers$state
year <- 2021

# création du tibble pour générer les rapports

reports <- tibble(
  input = "report.Rmd",
  output_file = str_c("output/", id, "-driving-", format(Sys.time(), "%Y%m%d%l%M"), ".html"),
  params = map(id, ~list(id = . , year = year))
)

# génération du rapport en boucle avec pwalk.

reports %>%
  pwalk(render)



# configurer Microsoft365R et ça marche !!!!

library(Microsoft365R)
outlb <- get_business_outlook()

library(blastula)
bl_body <- "## Hello!

This is an email message that was generated by the blastula package.

We can use **Markdown** formatting with the `md()` function.

Cheers,

The blastula team"

bl_em <- compose_email(
  body=md(bl_body),
  footer=md("sent via Microsoft365R")
)
em <- outlb$create_email(bl_em, subject="Hello from R", to="nic.bressoud@protonmail.ch")

# add an attachment and send it
em$add_attachment("output/Alabama.html")
em$send()

# list the most recent emails in your inbox
emlst <- outlb$list_emails()

# reply to the most recent email
emlst[[1]]$
  create_reply("Replying from R")$
  send()